In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.options.display.max_columns = None

In [3]:
#mouting the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
%cd drive/MyDrive/TFG/oulad

/content/drive/MyDrive/TFG/oulad

In [5]:
df_main = pd.read_csv('dataset_numerical.csv')

In [6]:
df_main.head()

,Unnamed: 0.1,Unnamed: 0,id_student,date_registration,date_unregistration,gender,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,mean_score,total_clicks,clicks_from_dataplus,clicks_from_forumng,clicks_from_homepage,clicks_from_oucontent,clicks_from_resource,clicks_from_subpage,clicks_from_url,clicks_from_externalquiz,clicks_from_oucollaborate,clicks_from_ouwiki,clicks_from_quiz,clicks_from_page,clicks_from_glossary,clicks_from_ouelluminate,clicks_from_dualpane,clicks_from_folder,clicks_from_questionnaire,clicks_from_htmlactivity,clicks_from_sharedsubpage,clicks_from_repeatactivity,mean_clicks,continuous_grade,exam_grade,module_presentation_length,mean_clicks_per_day,final_grade,code_module_AAA,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013B,code_presentation_2013J,code_presentation_2014B,code_presentation_2014J,region_East Anglian Region,region_East Midlands Region,region_Ireland,region_London Region,region_North Region,region_North Western Region,region_Scotland,region_South East Region,region_South Region,region_South West Region,region_Wales,region_West Midlands Region,region_Yorkshire Region,result_stays,result_aprueba
0,0,0,11391,-159.0,268.0,0,3,95.0,2,0,240,0,82.0,934.0,0.0,193.0,138.0,553.0,13.0,32.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.765306,82.4,82.4,268,0.017781,82.4,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1
1,1,1,28400,-53.0,268.0,1,3,25.0,1,0,60,0,66.4,1435.0,10.0,417.0,324.0,537.0,12.0,87.0,48.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.337209,65.4,65.4,268,0.012452,65.4,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1
2,2,2,30268,-92.0,12.0,1,2,35.0,1,0,60,1,0.0,281.0,0.0,126.0,59.0,66.0,4.0,22.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.697368,0.0,0.0,268,0.013796,0.0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2
3,3,3,31604,-52.0,268.0,1,2,55.0,1,0,60,0,76.0,2158.0,2.0,634.0,432.0,836.0,19.0,144.0,90.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.254902,76.3,76.3,268,0.012145,76.3,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
4,4,4,32885,-176.0,268.0,1,1,55.0,0,0,60,0,54.4,1034.0,0.0,194.0,204.0,494.0,45.0,79.0,14.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.937500,55.0,55.0,268,0.010961,55.0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1

In [7]:
df_main= df_main.drop(	['Unnamed: 0', 'Unnamed: 0.1', 'id_student', 'date_unregistration', 'clicks_from_externalquiz', 'clicks_from_oucollaborate', 'clicks_from_page', 'clicks_from_ouelluminate', 'clicks_from_dualpane', 'clicks_from_folder', 'clicks_from_htmlactivity',	'clicks_from_sharedsubpage',	'clicks_from_repeatactivity'], axis='columns')

In [8]:
df_main.head()

,date_registration,gender,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,mean_score,total_clicks,clicks_from_dataplus,clicks_from_forumng,clicks_from_homepage,clicks_from_oucontent,clicks_from_resource,clicks_from_subpage,clicks_from_url,clicks_from_ouwiki,clicks_from_quiz,clicks_from_glossary,clicks_from_questionnaire,mean_clicks,continuous_grade,exam_grade,module_presentation_length,mean_clicks_per_day,final_grade,code_module_AAA,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013B,code_presentation_2013J,code_presentation_2014B,code_presentation_2014J,region_East Anglian Region,region_East Midlands Region,region_Ireland,region_London Region,region_North Region,region_North Western Region,region_Scotland,region_South East Region,region_South Region,region_South West Region,region_Wales,region_West Midlands Region,region_Yorkshire Region,result_stays,result_aprueba
0,-159.0,0,3,95.0,2,0,240,0,82.0,934.0,0.0,193.0,138.0,553.0,13.0,32.0,5.0,0.0,0.0,0.0,0.0,4.765306,82.4,82.4,268,0.017781,82.4,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1
1,-53.0,1,3,25.0,1,0,60,0,66.4,1435.0,10.0,417.0,324.0,537.0,12.0,87.0,48.0,0.0,0.0,0.0,0.0,3.337209,65.4,65.4,268,0.012452,65.4,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1
2,-92.0,1,2,35.0,1,0,60,1,0.0,281.0,0.0,126.0,59.0,66.0,4.0,22.0,4.0,0.0,0.0,0.0,0.0,3.697368,0.0,0.0,268,0.013796,0.0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2
3,-52.0,1,2,55.0,1,0,60,0,76.0,2158.0,2.0,634.0,432.0,836.0,19.0,144.0,90.0,0.0,0.0,1.0,0.0,3.254902,76.3,76.3,268,0.012145,76.3,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
4,-176.0,1,1,55.0,0,0,60,0,54.4,1034.0,0.0,194.0,204.0,494.0,45.0,79.0,14.0,0.0,0.0,4.0,0.0,2.937500,55.0,55.0,268,0.010961,55.0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1

In [9]:
df_withdraws=df_main.copy()

In [10]:
del df_withdraws['result_aprueba']

In [11]:
df_pass=df_main.copy()

In [12]:
df_pass=df_pass[df_pass['result_stays']==1]

In [13]:
del df_pass['result_stays']

In [14]:
df_pass.result_aprueba.value_counts()

1    12361
0     7052
Name: result_aprueba, dtype: int64

In [15]:
df_withdraws.result_stays.value_counts()

1    19413
0    13180
Name: result_stays, dtype: int64

In [16]:
# Importar librerías
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

/usr/local/lib/python3.9/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(

In [17]:
# Separar las variables de entrada y la variable de salida
X = df_withdraws.loc[:, df_withdraws.columns != 'result_stays']
y = df_withdraws.result_stays

In [ ]:
# Split the data into training and test sets
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Split the training set into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42)

# Define the classifiers to use
svm_clf = SVC()
logreg_clf = LogisticRegression()
knn_clf = KNeighborsClassifier()
rf_clf = RandomForestClassifier()
dt_clf = DecisionTreeClassifier()
nb_clf = GaussianNB()
ada_clf = AdaBoostClassifier()
gb_clf = GradientBoostingClassifier()
xgb_clf =XGBClassifier()
lgbm_clf=LGBMClassifier()
arf_clf=HistGradientBoostingClassifier()


# Define the parameter grids to search over for each classifier
param_grid_svm = {
    'svm__C': [0.1, 1, 10, 100],
    'svm__kernel': ['linear', 'rbf', 'poly'],
    'svm__gamma': ['scale', 'auto']
}

param_grid_logreg = {
    'logreg__C': [0.1, 1, 10, 100],
    'logreg__penalty': ['l1', 'l2']
}

param_grid_knn = {
    'knn__n_neighbors': [3, 5, 7],
    'knn__weights': ['uniform', 'distance']
}

param_grid_rf = {
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [5, 10, 15],
    'rf__max_features': ['sqrt', 'log2']
}

param_grid_dt = {
    'dt__max_depth': [5, 10, 15],
    'dt__max_features': ['sqrt', 'log2']
}

param_grid_nb = {}

param_grid_ada = {
    'ada__n_estimators': [50, 100, 200],
    'ada__learning_rate': [0.1, 1, 10]
}

param_grid_gb = {
    'gb__n_estimators': [50, 100, 200],
    'gb__learning_rate': [0.1, 1, 10],
    'gb__max_depth': [5, 10, 15]
}

param_grid_xgb = {
"xgb__max_depth": [3, 5, 10],
"xgb__learning_rate": [0.1, 0.01, 0.001],
"xgb__n_estimators": [50, 100, 200],
}

param_grid_lgbm = {
"lgbm__max_depth": [3, 5, 10],
"lgbm__learning_rate": [0.1, 0.01, 0.001],
"lgbm__n_estimators": [50, 100, 200],
}

param_grid_arf = {
"arf__max_iter": [50, 100, 200],
"arf__max_depth": [3, 5, 10],
"arf__learning_rate": [0.1, 0.01, 0.001],
}


# Create pipelines for each classifier
svm_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', svm_clf)
])

logreg_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', logreg_clf)
])

knn_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', knn_clf)
])

rf_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('rf', rf_clf)
])

dt_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('dt', dt_clf)
])

nb_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('nb', nb_clf)
])

ada_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('ada', ada_clf)
])

gb_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('gb', gb_clf)
])

# Pipeline for XGBoost
xgb_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('xgb', xgb_clf)
])

# Pipeline for LightGBM
lgbm_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('lgbm', lgbm_clf)
])

# Pipeline for Adaptive Random Forest
arf_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('arf', arf_clf)
])

# Create GridSearchCV objects for each pipeline and parameter grid
svm_grid_search = GridSearchCV(svm_pipeline, param_grid_svm, cv=2, n_jobs=-1)
logreg_grid_search = GridSearchCV(logreg_pipeline, param_grid_logreg, cv=2, n_jobs=-1)
knn_grid_search = GridSearchCV(knn_pipeline, param_grid_knn, cv=2, n_jobs=-1)
rf_grid_search = GridSearchCV(rf_pipeline, param_grid_rf, cv=2, n_jobs=-1)
dt_grid_search = GridSearchCV(dt_pipeline, param_grid_dt, cv=2, n_jobs=-1)
nb_grid_search = GridSearchCV(nb_pipeline, param_grid_nb, cv=2, n_jobs=-1)
ada_grid_search = GridSearchCV(ada_pipeline, param_grid_ada, cv=2, n_jobs=-1)
gb_grid_search = GridSearchCV(gb_pipeline, param_grid_gb, cv=2, n_jobs=-1)
xgb_grid_search = GridSearchCV(xgb_pipeline, param_grid_xgb, cv=2, n_jobs=-1)
lgbm_grid_search = GridSearchCV(lgbm_pipeline, param_grid_lgbm, cv=2, n_jobs=-1)
arf_grid_search = GridSearchCV(arf_pipeline, param_grid_arf, cv=2, n_jobs=-1)

svm_grid_search.fit(X_train, y_train)
logreg_grid_search.fit(X_train, y_train)
knn_grid_search.fit(X_train, y_train)
rf_grid_search.fit(X_train, y_train)
dt_grid_search.fit(X_train, y_train)
nb_grid_search.fit(X_train, y_train)
ada_grid_search.fit(X_train, y_train)
gb_grid_search.fit(X_train, y_train)
xgb_grid_search.fit(X_train, y_train)
lgbm_grid_search.fit(X_train, y_train)
arf_grid_search.fit(X_train, y_train)




# Print the best parameters and score found during the search for each classifier
print("SVM - Best parameters:", svm_grid_search.best_params_)
print("SVM - Best score:", svm_grid_search.best_score_)
svm_best_model = svm_grid_search.best_estimator_
svm_val_score = svm_best_model.score(X_val, y_val)
print("SVM - Validation score:", svm_val_score)
svm_test_score = svm_best_model.score(X_test, y_test)
print("SVM - Test score:", svm_test_score)

print("Logistic Regression - Best parameters:", logreg_grid_search.best_params_)
print("Logistic Regression - Best score:", logreg_grid_search.best_score_)
logreg_best_model = logreg_grid_search.best_estimator_
logreg_val_score = logreg_best_model.score(X_val, y_val)
print("Logistic Regression - Validation score:", logreg_val_score)
logreg_test_score = logreg_best_model.score(X_test, y_test)
print("Logistic Regression - Test score:", logreg_test_score)

print("KNN - Best parameters:", knn_grid_search.best_params_)
print("KNN - Best score:", knn_grid_search.best_score_)
knn_best_model = knn_grid_search.best_estimator_
knn_val_score = knn_best_model.score(X_val, y_val)
print("KNN - Validation score:", knn_val_score)
knn_test_score = knn_best_model.score(X_test, y_test)
print("KNN - Test score:", knn_test_score)

print("Random Forest - Best parameters:", rf_grid_search.best_params_)
print("Random Forest - Best score:", rf_grid_search.best_score_)
rf_best_model = rf_grid_search.best_estimator_
rf_val_score = rf_best_model.score(X_val, y_val)
print("Random Forest - Validation score:", rf_val_score)
rf_test_score = rf_best_model.score(X_test, y_test)
print("Random Forest - Test score:", rf_test_score)

print("Decision Tree - Best parameters:", dt_grid_search.best_params_)
print("Decision Tree - Best score:", dt_grid_search.best_score_)
dt_best_model = dt_grid_search.best_estimator_
dt_val_score = dt_best_model.score(X_val, y_val)
print("Decision Tree - Validation score:", dt_val_score)
dt_test_score = dt_best_model.score(X_test, y_test)
print("Decision Tree - Test score:", dt_test_score)

print("Naive Bayes - Best parameters:", nb_grid_search.best_params_)
print("Naive Bayes - Best score:", nb_grid_search.best_score_)
nb_best_model = nb_grid_search.best_estimator_
nb_val_score = nb_best_model.score(X_val, y_val)
print("Naive Bayes - Validation score:", nb_val_score)
nb_test_score = nb_best_model.score(X_test, y_test)
print("Naive Bayes - Test score:", nb_test_score)

print("AdaBoost - Best parameters:", ada_grid_search.best_params_)
print("AdaBoost - Best score:", ada_grid_search.best_score_)
ada_best_model = ada_grid_search.best_estimator_
ada_val_score = ada_best_model.score(X_val, y_val)
print("AdaBoost - Validation score:", ada_val_score)
ada_test_score = ada_best_model.score(X_test, y_test)
print("AdaBoost - Test score:", ada_test_score)

print("Gradient Boosting - Best parameters:", gb_grid_search.best_params_)
print("Gradient Boosting - Best score:", gb_grid_search.best_score_)
gb_best_model = gb_grid_search.best_estimator_
gb_val_score = gb_best_model.score(X_val, y_val)
print("Gradient Boosting - Validation score:", gb_val_score)
gb_test_score = gb_best_model.score(X_test, y_test)
print("Gradient Boosting - Test score:", gb_test_score)

# Print best parameters, best validation score, and test score for XGBoost
print("XGBoost - Best parameters:", xgb_grid_search.best_params_)
print("XGBoost - Best score:", xgb_grid_search.best_score_)
xgb_best_model = xgb_grid_search.best_estimator_
xgb_val_score = xgb_best_model.score(X_val, y_val)
print("XGBoost - Validation score:", xgb_val_score)
xgb_test_score = xgb_best_model.score(X_test, y_test)
print("XGBoost - Test score:", xgb_test_score)

# Print best parameters, best validation score, and test score for LightGBM
print("LightGBM - Best parameters:", lgbm_grid_search.best_params_)
print("LightGBM - Best score:", lgbm_grid_search.best_score_)
lgbm_best_model = lgbm_grid_search.best_estimator_
lgbm_val_score = lgbm_best_model.score(X_val, y_val)
print("LightGBM - Validation score:", lgbm_val_score)
lgbm_test_score = lgbm_best_model.score(X_test, y_test)
print("LightGBM - Test score:", lgbm_test_score)

# Print best parameters, best validation score, and test score for Adaptive Random Forest
print("Adaptive Random Forest - Best parameters:", arf_grid_search.best_params_)
print("Adaptive Random Forest - Best score:", arf_grid_search.best_score_)
arf_best_model = arf_grid_search.best_estimator_
arf_val_score = arf_best_model.score(X_val, y_val)
print("Adaptive Random Forest - Validation score:", arf_val_score)
arf_test_score = arf_best_model.score(X_test, y_test)
print("Adaptive Random Forest - Test score:", arf_test_score)

C:\Users\lulug\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lulug\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

SVM - Best parameters: {'svm__C': 1, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}
SVM - Best score: 0.7799539759652263
SVM - Validation score: 0.7853965332106151
SVM - Test score: 0.7834023623255101
Logistic Regression - Best parameters: {'logreg__C': 0.1, 'logreg__penalty': 'l1'}
Logistic Regression - Best score: 0.7483508054206085
Logistic Regression - Validation score: 0.7505752416014726
Logistic Regression - Test score: 0.7452063199877281
KNN - Best parameters: {'knn__n_neighbors': 7, 'knn__weights': 'uniform'}
KNN - Best score: 0.7360265916645359
KNN - Validation score: 0.7402975916551618
KNN - Test score: 0.7373830342077006
Random Forest - Best parameters: {'rf__max_depth': 10, 'rf__max_features': 'sqrt', 'rf__n_estimators': 200}
Random Forest - Best score: 0.8058297110713373
Random Forest - Validation score: 0.8041110599785243
Random Forest - Test score: 0.798128547323209
Decision Tree - Best parameters: {'dt__max_depth': 10, 'dt__max_features': 'sqrt'}
Decision Tree - Best score: 0.7744310917923805
Decision Tree - Validation score: 0.7712839392544869
Decision Tree - Test score: 0.7726645190980211
Naive Bayes - Best parameters: {}
Naive Bayes - Best score: 0.6816159549987215
Naive Bayes - Validation score: 0.7014879582758091
Naive Bayes - Test score: 0.6804724651020095
AdaBoost - Best parameters: {'ada__learning_rate': 1, 'ada__n_estimators': 200}
AdaBoost - Best score: 0.7926872922526207
AdaBoost - Validation score: 0.7944470010737843
AdaBoost - Test score: 0.7907654548243596
Gradient Boosting - Best parameters: {'gb__learning_rate': 0.1, 'gb__max_depth': 5, 'gb__n_estimators': 100}
Gradient Boosting - Best score: 0.8084888775249297
Gradient Boosting - Validation score: 0.8050314465408805
Gradient Boosting - Test score: 0.805798435342844
XGBoost - Best parameters: {'xgb__learning_rate': 0.1, 'xgb__max_depth': 3, 'xgb__n_estimators': 200}
XGBoost - Best score: 0.8072104321145487
XGBoost - Validation score: 0.8091731860714834
XGBoost - Test score: 0.8039576622181316
LightGBM - Best parameters: {'lgbm__learning_rate': 0.1, 'lgbm__max_depth': 10, 'lgbm__n_estimators': 100}
LightGBM - Best score: 0.8081820506264382
LightGBM - Validation score: 0.8067188219052002
LightGBM - Test score: 0.8076392084675563
Adaptive Random Forest - Best parameters: {'arf__learning_rate': 0.1, 'arf__max_depth': 5, 'arf__max_iter': 100}
Adaptive Random Forest - Best score: 0.8072104321145487
Adaptive Random Forest - Validation score: 0.8067188219052002
Adaptive Random Forest - Test score: 0.8076392084675563